### ISSUE TITLE
Algorithm for finding LRS

### ISSUE THREAD

**Issue by himito** [wangsix/vmo#15]
Hi,

I saw that vmo implements the algorithm found at  

> Lefebvre, A., Lecroq, T., & Alexandre, J. (2003). An Improved Algorithm for Finding Longest Repeats with a Modified Factor Oracle. Journal of Automata, Languages and Combinatorics, 8(4), 647–657.

However, the factor oracle for the string `abbcabcdabc` built by vmo does not correspond to the shown in the paper (figure below). VMO returns `lrs[11] = 2` and `sfx[11] = 4`

<img width="573" alt="capture d ecran 2016-09-13 a 11 35 39" src="https://cloud.githubusercontent.com/assets/181677/18468897/3f93a35e-79a6-11e6-82c2-6e9152df9f47.png">
 
Cheers, 
Jaime.

**Comment by wangsix** [comment]
Fixed by @himito.
