### ISSUE TITLE
Direct access to undocumented class attribute 'latent'

### ISSUE THREAD

**Issue by tbazin** [wangsix/vmo#7]
@wangsix Both demo notebooks use direct accesses to `VMO.latent`. Furthermore, this method is not documented in the class' definition.

Consider creating a method to access this attribute if it is really needed, in order to respect the encapsulation principle.

**Comment by wangsix** [comment]
@tbazin Thank you so much for the suggestion. I just updated the documentation for the `mo.latent` attribute and some others. 

I have been developing this module by myself so there was no other eyes looking at where could be improved. Great appreciation for your suggestion.

**Comment by tbazin** [comment]
Pleasure is mine!
I'm finally starting to get a hang of what's going on in here, so expect some more issues/commits :smile:
